I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level/telefonoConversacion.rpy", line 16, in script
    show expression "pantalla_bloqueo_[jugador.nombre]":
Exception: DynamicImage 'pantalla_bloqueo_[jugador.nombre]': could not find image. ('pantalla_bloqueo_???')

-- Full Traceback ------------------------------------------------------------

Traceback (most recent call last):
  File "game/level/telefonoConversacion.rpy", line 16, in script
    show expression "pantalla_bloqueo_[jugador.nombre]":
  File "renpy/ast.py", line 1357, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "renpy/ast.py", line 730, in show_imspec
    renpy.config.show(
    ~~~~~~~~~~~~~~~~~^
        name, at_list=at_list, layer=layer, what=expression, zorder=zorder, tag=tag, behind=behind, atl=atl
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/exports/displayexports.py", line 513, in show
    sls.add(
    ~~~~~~~^
        layer,
        ^^^^^^
    ...<8 lines>...
        transient=transient,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "renpy/display/scenelists.py", line 453, in add
    thing.set_transform_event("show")
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "renpy/display/transform.py", line 862, in set_transform_event
    self.child.set_transform_event(event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "renpy/display/image.py", line 775, in set_transform_event
    self.find_target()
    ~~~~~~~~~~~~~~~~^^
  File "renpy/display/image.py", line 699, in find_target
    raise Exception(error)
Exception: DynamicImage 'pantalla_bloqueo_[jugador.nombre]': could not find image. ('pantalla_bloqueo_???')

Windows-11-10.0.26100-SP0 AMD64
Ren'Py 8.4.1.25072401
Latencia

Me quiere o no me quiere, pero ¿cómo quiero? 1.0.0-alpha
Wed Oct 15 18:25:49 2025
